### ISSUE TITLE
some questions about DifferentialTransformer

### ISSUE THREAD

**Issue by morestart** [kyegomez/DifferentialTransformer#5]
The variable λ in the forward function of the DifferentialTransformer class is not being used. Is it necessary to pass it? Regarding the initialization of λ, should the following function be used:

```python
def lambda_init_fn(depth):
    return 0.8 - 0.6 * math.exp(-0.3 * depth)
```

**Comment by yiersan1760** [comment]
Is it necessary to pass it?
